name: Test Action

on:
  pull_request:
  push:
    branches:
      - '*'

permissions:
  contents: write
  pull-requests: write
  checks: write
  actions: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
           dependencies.enabled: false
           policies: copyleft, und
           policies.halt_on_failure: 'false'
           api.key: ${{ secrets.SC_API_KEY }}


      - name: Print stdout scan command
        run: echo "${{ steps.test-action.outputs.stdout-scan-command }}"

      - name: Print Results
        run: cat "${{ steps.test-action.outputs.result-filepath }}"
